version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: Test123
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:11.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: Test123
volumes:
  postgres: